site_name: 'Taller de LaTeX'
site_author: 'Pablo Rodríguez Guillén <pablorodriguezguillen@gmail.com>'
site_description: 'Taller de introducción a LaTeX'
site_url: 'https://github.com/aulasoftwarelibre/taller-de-latex.git'

repo_name: 'aulasoftwarelibre/taller-de-latex'
repo_url: 'https://github.com/aulasoftwarelibre/taller-de-latex.git'

theme:
  name: 'material'
  language: 'es'
  favicon: 'images/logoasl.svg'
  features:
    - instant

plugins:
  - awesome-pages
  - search

extra_css: [extra.css]
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/aulasoftwarelibre'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/aulasl'
    - icon: fontawesome/brands/facebook
      link: 'https://facebook.com/aulasl'
    - icon: fontawesome/brands/instagram
      link: 'https://instagram.com/aulasoftwarelibre'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCfWiR5j-cbKcGTi9faK8P6w'

markdown_extensions:
  - admonition: ~
  - attr_list: ~
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list: ~
  - footnotes: ~
  - toc:
      permalink: true
  - pymdownx.keys: ~

google_analytics:
  - 'UA-51754922-1'
  - 'auto'
